# Generated by Django 3.2.7 on 2021-10-08 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('familystructure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BaseReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('heart', 'Heart'), ('smiley', 'Smiley'), ('thumbs_up', 'Thumbs_up')], default='thumbs_up', max_length=12)),
                ('reactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_made', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('family_circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='familystructure.familycircle', verbose_name='family circle')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='content')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='sent_at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_made', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_made', to=settings.AUTH_USER_MODEL)),
                ('commented_on', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='socialmedia.post')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='members')),
                ('messages', models.ManyToManyField(blank=True, related_name='chat', to='socialmedia.Message', verbose_name='messages')),
            ],
        ),
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('basereaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socialmedia.basereaction')),
                ('target_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reactions', to='socialmedia.post')),
            ],
            bases=('socialmedia.basereaction',),
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('basereaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socialmedia.basereaction')),
                ('target_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to='socialmedia.message')),
            ],
            bases=('socialmedia.basereaction',),
        ),
        migrations.CreateModel(
            name='MessageNotification',
            fields=[
                ('basenotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socialmedia.basenotification')),
                ('target_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_notifications', to='socialmedia.message')),
            ],
            bases=('socialmedia.basenotification',),
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('basereaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socialmedia.basereaction')),
                ('target_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reactions', to='socialmedia.comment')),
            ],
            bases=('socialmedia.basereaction',),
        ),
        migrations.CreateModel(
            name='CommentNotification',
            fields=[
                ('basenotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socialmedia.basenotification')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_notifications', to='socialmedia.comment')),
            ],
            bases=('socialmedia.basenotification',),
        ),
    ]
