# Generated by Django 3.2.7 on 2021-10-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(choices=[('heart', 'Heart'), ('smiley', 'Smiley'), ('thumbs_up', 'Thumbs_up')], default='thumbs_up', max_length=12),
        ),
    ]
