# Generated by Django 3.2.7 on 2021-10-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_photo',
            field=models.ImageField(blank=True, null=True, upload_to='post_photos/', verbose_name='post photo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
