# Generated by Django 3.2.7 on 2021-10-07 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialmedia', '0002_auto_20211007_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_is', models.BooleanField(choices=[(True, 'Like'), (False, 'Dislike')])),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('author', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reaction', to=settings.AUTH_USER_MODEL)),
                ('post_reaction', models.ManyToManyField(blank=True, related_name='reactions', to='socialmedia.Post')),
            ],
        ),
    ]
