# Generated by Django 3.2.7 on 2021-10-08 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0002_auto_20211008_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentnotification',
            old_name='target',
            new_name='target_comment',
        ),
    ]
