# Generated by Django 3.2.7 on 2021-10-08 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('familystructure', '0001_initial'),
        ('socialmedia', '0002_alter_reaction_reaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.useraccount', verbose_name='author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='family_circle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='familystructure.familycircle', verbose_name='author'),
            preserve_default=False,
        ),
    ]
