# Generated by Django 3.2.7 on 2021-10-08 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0003_rename_target_commentnotification_target_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageReaction',
        ),
    ]
