# Generated by Django 3.2.7 on 2021-10-08 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familystructure', '0001_initial'),
        ('socialmedia', '0003_auto_20211008_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post_comment_added',
        ),
        migrations.AddField(
            model_name='comment',
            name='commented_on',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commented_on', to='socialmedia.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='family_circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familystructure.familycircle', verbose_name='family circle'),
        ),
    ]
