# Generated by Django 3.2.7 on 2021-10-08 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialmedia', '0004_auto_20211008_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentnotification',
            name='author_inform',
        ),
        migrations.RemoveField(
            model_name='commentnotification',
            name='post_notify',
        ),
        migrations.AddField(
            model_name='commentnotification',
            name='target_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='target_author', to='useraccount.useraccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentnotification',
            name='target_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='target_comment', to='socialmedia.comment'),
            preserve_default=False,
        ),
    ]
