# Generated by Django 3.2.7 on 2021-10-11 19:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0004_delete_messagereaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='basenotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created_at'),
            preserve_default=False,
        ),
    ]
