# Generated by Django 3.2.7 on 2021-10-08 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialmedia', '0005_auto_20211008_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='post_reaction',
        ),
        migrations.AddField(
            model_name='comment',
            name='reactions',
            field=models.ManyToManyField(related_name='comment_reactions', to='socialmedia.Reaction', verbose_name='reactions'),
        ),
        migrations.AddField(
            model_name='post',
            name='reactions',
            field=models.ManyToManyField(related_name='post_reactions', to='socialmedia.Reaction', verbose_name='reactions'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='reactor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactor', to=settings.AUTH_USER_MODEL),
        ),
    ]
