# Generated by Django 3.2.7 on 2021-10-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0006_auto_20211008_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reactions',
            field=models.ManyToManyField(related_name='comment_reactions', related_query_name='reactions', to='socialmedia.Reaction', verbose_name='reactions'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reactions',
            field=models.ManyToManyField(related_name='post_reactions', related_query_name='reactions', to='socialmedia.Reaction', verbose_name='reactions'),
        ),
    ]
