# Generated by Django 3.2.7 on 2021-10-08 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialmedia', '0007_auto_20211008_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BaseReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('heart', 'Heart'), ('smiley', 'Smiley'), ('thumbs_up', 'Thumbs_up')], default='thumbs_up', max_length=12)),
                ('reactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reactions',
        ),
        migrations.RemoveField(
            model_name='commentnotification',
            name='id',
        ),
        migrations.RemoveField(
            model_name='commentnotification',
            name='target_author',
        ),
        migrations.RemoveField(
            model_name='commentnotification',
            name='target_comment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reactions',
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('basereaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socialmedia.basereaction')),
            ],
            bases=('socialmedia.basereaction',),
        ),
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('basereaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socialmedia.basereaction')),
            ],
            bases=('socialmedia.basereaction',),
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
        migrations.AddField(
            model_name='commentnotification',
            name='basenotification_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socialmedia.basenotification'),
            preserve_default=False,
        ),
    ]
