# Generated by Django 3.2.7 on 2021-10-08 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0008_auto_20211008_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentnotification',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment_notification', to='socialmedia.comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentreaction',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment_reaction', to='socialmedia.comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postreaction',
            name='target_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_reaction', to='socialmedia.post'),
            preserve_default=False,
        ),
    ]
