# Generated by Django 3.2.7 on 2021-10-13 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familystructure', '0002_initial'),
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='useraccount', to='familystructure.person', verbose_name='person'),
        ),
    ]
