# Generated by Django 3.2.7 on 2021-10-08 17:58

from django.db import migrations, models
import django.db.models.deletion
import familystructure.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='first name')),
                ('nickname', models.CharField(blank=True, max_length=32, null=True, verbose_name='nickname')),
                ('middle_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='middle name')),
                ('last_name', models.CharField(max_length=32, verbose_name='last name')),
                ('title', models.CharField(blank=True, max_length=16, null=True, verbose_name='title')),
                ('tagline', models.CharField(blank=True, max_length=64, null=True, verbose_name='tagline')),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('is_claimed', models.BooleanField(default=False, verbose_name='is claimed')),
                ('facts', familystructure.fields.ListAsStringField(blank=True, default='[]', null=True)),
            ],
            options={
                'verbose_name_plural': 'people',
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_upward', models.BooleanField(default=True, verbose_name='is upward')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='familystructure.person', verbose_name='source person')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='familystructure.person', verbose_name='target person')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyCircle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('managers', models.ManyToManyField(related_name='managers', to='familystructure.Person', verbose_name='managers')),
                ('members', models.ManyToManyField(related_name='members', to='familystructure.Person', verbose_name='members')),
            ],
        ),
    ]
