# Generated by Django 3.2.7 on 2021-10-12 00:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('familystructure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='familycircle',
            name='managers',
            field=models.ManyToManyField(related_name='managers', to=settings.AUTH_USER_MODEL, verbose_name='managers'),
        ),
        migrations.AddField(
            model_name='familycircle',
            name='members',
            field=models.ManyToManyField(related_name='members', to='familystructure.Person', verbose_name='members'),
        ),
    ]
