# Generated by Django 3.2.7 on 2021-10-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familystructure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familycircle',
            name='name',
            field=models.CharField(default='The Doe Family', max_length=64, verbose_name='name'),
            preserve_default=False,
        ),
    ]
