# Generated by Django 3.2.7 on 2021-10-07 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('directmessaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='sent_at'),
            preserve_default=False,
        ),
    ]
