# Generated by Django 3.2.7 on 2021-10-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directmessaging', '0002_message_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='messages',
            field=models.ManyToManyField(blank=True, null=True, to='directmessaging.Message', verbose_name='messages'),
        ),
    ]
